version: '3'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      # For local development of toast-value-store
      # - ADVERTISED_HOST_NAME=192.168.1.4
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250
  #schema-registry:
  #  image: apicurio/apicurio-registry-mem:2.4.3.Final
  #  ports:
  #    - 8082:8080
  #  links:
  #    - zookeeper
  #  environment:
  #    - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
  #    - SCHEMA_REGISTRY_HOST_NAME=schema-registry
  #    - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
  source-db:
    image: debezium-lab/toast-source-db:${DEBEZIUM_VERSION}
    build:
      context: source-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresusersource
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=sourcedb
  sink-db:
    image: debezium-lab/toast-sink-db:${DEBEZIUM_VERSION}
    build:
      context: sink-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgresusersink
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=sinkdb
  connect:
    image: debezium-lab/toast-connect:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc
    ports:
      - 8083:8083
    links:
      - kafka
      - source-db
      - sink-db
      #- schema-registry
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
      - ENABLE_DEBEZIUM_KC_REST_EXTENSION=true
      - ENABLE_DEBEZIUM_SCRIPTING=true
      - CONNECT_REST_EXTENSION_CLASSES=io.debezium.kcrestextension.DebeziumConnectRestExtension
      #- ENABLE_APICURIO_CONVERTERS=true
      #- KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
      #- VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
      #- CONNECT_KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
      #- CONNECT_KEY_CONVERTER_APICURIO.REGISTRY_URL=http://schema-registry:8080/apis/registry/v2
      #- CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER=true
      #- CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_FIND-LATEST=true
      #- CONNECT_VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
      #- CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL=http://schema-registry:8080/apis/registry/v2
      #- CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER=true
      #- CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_FIND-LATEST=true
      #- CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE=avro
  debezium-ui:
    container_name: debezium-ui
    image: debezium/debezium-ui:${DEBEZIUM_VERSION}
    ports:
      - "8080:8080"
    links:
      - connect
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8081:8080
    links:
      - connect
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: debezium
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.1
    command: docs serve --port 8001
    working_dir: /home/dbt
    links:
      - sink-db
    volumes:
      - ./dbt:/home/dbt
    ports:
      - "8001:8001"
    environment:
      - DBT_DB_NAME=sinkdb
      - DBT_USER=postgresusersink
      - DBT_PASS=postgrespw
      - DBT_HOST=sink-db
